"""Constants for the shm2mqtt integration."""
from dataclasses import dataclass

from collections.abc import Callable
import voluptuous as vol

import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.entity import EntityCategory
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    Platform,
    POWER_VOLT_AMPERE_REACTIVE,
    DEGREE,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfApparentPower,
    UnitOfElectricPotential,
    UnitOfElectricCurrent,
    UnitOfFrequency,
)

PLATFORMS = [
    Platform.SENSOR,
]


# Global values
DOMAIN = "shm2mqtt"
MQTT_ROOT_TOPIC = "mqttroot"
MQTT_ROOT_TOPIC_DEFAULT = "SHM2"
MANUFACTURER = "SMA"
MODEL = "SHM2"
SERIAL = "serial"
SERIAL_DEFAULT = "3015975172"


# Data schema required by configuration flow
DATA_SCHEMA = vol.Schema(
    {
        vol.Required(MQTT_ROOT_TOPIC, default=MQTT_ROOT_TOPIC_DEFAULT): cv.string,
        vol.Required(SERIAL, default=SERIAL_DEFAULT): cv.string,
    }
)


@dataclass
class Shm2SensorEntityDescription(SensorEntityDescription):
    """Enhance the sensor entity description for SHM2"""

    value_fn: Callable | None = None
    value_map: dict | None = None
    mqtt_current_value: str | None = None


SENSORS_SHM2 = [
    # device info
    Shm2SensorEntityDescription(
        key="device_info/name",
        name="Device name",
        device_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:camera-switch",
    ),
    Shm2SensorEntityDescription(
        key="device_info/identifiers",
        name="Device serial",
        device_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:camera-switch",
    ),
    Shm2SensorEntityDescription(
        key="device_info/model",
        name="Device model",
        device_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:camera-switch",
    ),
    Shm2SensorEntityDescription(
        key="device_info/manufacturer",
        name="Device manufacturer",
        device_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:camera-switch",
    ),
    Shm2SensorEntityDescription(
        key="device_info/sw_version",
        name="Device SW version",
        device_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:camera-switch",
    ),
    # global measurements
    Shm2SensorEntityDescription(
        key="p/pconsume",
        name="Active power consumption",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/pconsumecounter",
        name="Active power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="p/psupply",
        name="Active power supply",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/psupplycounter",
        name="Active power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/qconsume",
        name="Reactive power consumption",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/qconsumecounter",
        name="Reactive power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/qsupply",
        name="Reactive power supply",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/qsupplycounter",
        name="Reactive power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/sconsume",
        name="Apparent power consumption",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/sconsumecounter",
        name="Apparent power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/ssupply",
        name="Apparent power supply",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/ssupplycounter",
        name="Apparent power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="cosphi",
        name="Phase angle cosine",
        device_class=None,
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:cosine-wave",
    ),
    Shm2SensorEntityDescription(
        key="frequency",
        name="Grid frequency",
        device_class=SensorDeviceClass.FREQUENCY,
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:sine-wave",
    ),
    # phase 1 measurements
    Shm2SensorEntityDescription(
        key="p/1/p1consume",
        name="Phase 1 consumption",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/1/p1consumecounter",
        name="Phase 1 consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="p/1/p1supply",
        name="Phase 1 active power supply",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/1/p1supplycounter",
        name="Phase 1 supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/1/q1consume",
        name="Phase 1 reactive power consumption",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/1/q1consumecounter",
        name="Phase 1 reactive power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/1/q1supply",
        name="Phase 1 reactive power supply",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/1/q1supplycounter",
        name="Phase 1 reactive power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/1/s1consume",
        name="Phase 1 apparent power consumption",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/1/s1consumecounter",
        name="Phase 1 apparent power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/1/s1supply",
        name="Phase 1 apparent power supply",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/1/s1supplycounter",
        name="Phase 1 apparent power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="1/i1",
        name="Phase 1 current",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:current-ac",
    ),
    Shm2SensorEntityDescription(
        key="1/u1",
        name="Phase 1 potential",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    Shm2SensorEntityDescription(
        key="1/cosphi1",
        name="Phase 1 angle cosine",
        device_class=None,
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:cosine-wave",
    ),
    # phase 2 measurements
    Shm2SensorEntityDescription(
        key="p/2/p2consume",
        name="Phase 2 consumption",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/2/p2consumecounter",
        name="Phase 2 consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="p/2/p2supply",
        name="Phase 2 active power supply",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/2/p2supplycounter",
        name="Phase 2 supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/2/q2consume",
        name="Phase 2 reactive power consumption",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/2/q2consumecounter",
        name="Phase 2 reactive power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/2/q2supply",
        name="Phase 2 reactive power supply",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/2/q2supplycounter",
        name="Phase 2 reactive power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/2/s2consume",
        name="Phase 2 apparent power consumption",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/2/s2consumecounter",
        name="Phase 2 apparent power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/2/s2supply",
        name="Phase 2 apparent power supply",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/2/s2supplycounter",
        name="Phase 2 apparent power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="2/i2",
        name="Phase 2 current",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:current-ac",
    ),
    Shm2SensorEntityDescription(
        key="2/u2",
        name="Phase 2 potential",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    Shm2SensorEntityDescription(
        key="2/cosphi2",
        name="Phase 2 angle cosine",
        device_class=None,
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:cosine-wave",
    ),
    # phase 3 measurements
    Shm2SensorEntityDescription(
        key="p/3/p3consume",
        name="Phase 3 consumption",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/3/p3consumecounter",
        name="Phase 3 consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="p/3/p3supply",
        name="Phase 3 active power supply",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="p/3/p3supplycounter",
        name="Phase 3 supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/3/q3consume",
        name="Phase 3 reactive power consumption",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/3/q3consumecounter",
        name="Phase 3 reactive power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="q/3/q3supply",
        name="Phase 3 reactive power supply",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=POWER_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="q/3/q3supplycounter",
        name="Phase 3 reactive power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/3/s3consume",
        name="Phase 3 apparent power consumption",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/3/s3consumecounter",
        name="Phase 3 apparent power consumption counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="s/3/s3supply",
        name="Phase 3 apparent power supply",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:home-lightning-bolt-outline",
    ),
    Shm2SensorEntityDescription(
        key="s/3/s3supplycounter",
        name="Phase 3 apparent power supply counter",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kVAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        value_fn=lambda x: round(float(x)),
        icon="mdi:counter",
    ),
    Shm2SensorEntityDescription(
        key="3/i3",
        name="Phase 3 current",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:current-ac",
    ),
    Shm2SensorEntityDescription(
        key="3/u3",
        name="Phase 3 potential",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    Shm2SensorEntityDescription(
        key="3/cosphi3",
        name="Phase 3 angle cosine",
        device_class=None,
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:cosine-wave",
    ),
]
